# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 932cc12a7b829d3aacb7c2e4a2b2610c2e3c92f2c6c31e09a5c803351ee0ec544cf69f7d8bf9354c2f44baefd8e9ab2d01354163d8d5ece80d3abcc463ed8c56

test:
  secret_key_base: b39371fe8855931ef192758666a04eb780b46a4e945f40670fdf33b9017f9c097342ff212d38c01979289f2abc7d31e8736304f046131f34d71a95bfac7defd7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
